version: "2"
services:
  db:
    container_name: h2o_db
    image: h2o/db:1.0
    build:
      context: ..
      dockerfile: deploy/db/Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: h2o_db_password
  app:
    container_name: h2o_app
    image: h2o/app:1.0
    build:
      context: ..
      dockerfile: deploy/app_server/Dockerfile
    privileged: true
    links:
      - db
    expose:
      - 8080
    ports:
      - "18080:8080"
